name: flutter_application_1
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remueve esta línea si deseas publicar en pub.dev

# Versión de la aplicación
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.0+4
  shared_preferences: ^2.0.15  # Para almacenamiento local
  provider: ^6.0.5            # Para gestión del estado
  crypto: ^3.0.1              # Para encriptación (si se usa para passwords)
  flutter_localizations:     # Para las traducciones si es necesario
    sdk: flutter
  cupertino_icons: ^1.0.8     # Para usar iconos estilo iOS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0       # Paquete para sugerencias de buenas prácticas en código

flutter:

  # Para usar Material Design y los íconos correspondientes
  uses-material-design: true

  # Asegúrate de incluir las fuentes de iconos de Cupertino si estás usando widgets iOS
  assets:
    - assets/images/          # Ejemplo para agregar imágenes personalizadas dentro de la carpeta assets

# Esta sección es opcional y se puede agregar si estás usando ficheros para localización.
# Añade la localización de los idiomas que usas en tu app.
flutter_localizations:
  sdk: flutter





  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
